# Generated by Django 2.0.7 on 2018-07-22 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LastCpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='LastMemory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('hostid', models.CharField(max_length=500, null=True)),
                ('ip', models.CharField(max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('firewall', models.CharField(max_length=500, null=True)),
                ('mcafee', models.CharField(max_length=500, null=True)),
                ('maxusedmemory', models.CharField(max_length=500, null=True)),
                ('maxusedcpu', models.CharField(max_length=500, null=True)),
                ('freediskc', models.CharField(max_length=500, null=True)),
                ('freediskd', models.CharField(max_length=500, null=True)),
                ('freediske', models.CharField(max_length=500, null=True)),
                ('freediskf', models.CharField(max_length=500, null=True)),
                ('freediskg', models.CharField(max_length=500, null=True)),
                ('freediskh', models.CharField(max_length=500, null=True)),
                ('freediski', models.CharField(max_length=500, null=True)),
                ('telnet', models.CharField(max_length=500, null=True)),
                ('ssl_cert_exp', models.CharField(max_length=500, null=True)),
                ('win_active', models.CharField(max_length=500, null=True)),
                ('sql_login_user', models.CharField(max_length=500, null=True)),
                ('sql_xp_cmdshell', models.CharField(max_length=500, null=True)),
                ('sql_version', models.CharField(max_length=500, null=True)),
                ('sql_file_size', models.TextField(null=True)),
                ('open_port', models.TextField(null=True)),
                ('windows_version', models.CharField(max_length=500, null=True)),
                ('anydesk', models.CharField(max_length=500, null=True)),
                ('time_win_sync', models.CharField(max_length=500, null=True)),
                ('microsoft_update', models.CharField(max_length=500, null=True)),
                ('local_user', models.TextField(null=True)),
                ('backup_name', models.TextField(null=True)),
                ('smb1_config', models.CharField(max_length=500, null=True)),
                ('eventlog_max_size', models.TextField(null=True)),
                ('new_system_event', models.TextField(null=True)),
                ('new_app_event', models.TextField(null=True)),
                ('file_sharing_port', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SqlDataAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, null=True)),
                ('host', models.CharField(max_length=500, null=True)),
                ('server', models.CharField(max_length=500, null=True)),
                ('port', models.CharField(max_length=500, null=True)),
                ('user', models.CharField(max_length=500, null=True)),
                ('password', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lastmemory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memory', to='payeshapp.Server'),
        ),
        migrations.AddField(
            model_name='lastcpu',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpu', to='payeshapp.Server'),
        ),
    ]
