# Generated by Django 2.0.7 on 2018-07-22 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payeshapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastcpu',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cpu', to='payeshapp.Server'),
        ),
        migrations.AlterField(
            model_name='lastmemory',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='memory', to='payeshapp.Server'),
        ),
    ]
