# Generated by Django 2.0.7 on 2018-07-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payeshapp', '0002_auto_20180722_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='SslData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostip', models.CharField(max_length=500, null=True)),
                ('addr', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
